//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RdpCreator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=172.17.74.9;Port=3306;Uid=ms;Pwd=ms;Database=ms;character set=utf8")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT A1.ID ,concat( A1.Name,\'(\',A2.Name,\')\') as Name FROM  Attributes A1 join  " +
            "Attributes A2 on A1.Type=A2.ID where A1.Type>1")]
        public string AttributeQuery {
            get {
                return ((string)(this["AttributeQuery"]));
            }
            set {
                this["AttributeQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT W.ID , W.IP , W.Name ,ifnull( R.Name,W.Name) as RdpName ,ifnull( R.Domain," +
            "0)*1 as Domain\r\nFROM  WIN_server W left join RDP_ServerNames R on R.ServerID=W.I" +
            "D\r\nwhere W.Poll_Users!=0;")]
        public string ServerNames {
            get {
                return ((string)(this["ServerNames"]));
            }
            set {
                this["ServerNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT A.ServerID , A.AttributeID\r\nFROM   Server_Attributes A join WIN_server w o" +
            "n A.ServerID=w.ID\r\nwhere w.Poll_Users!=0;")]
        public string ServerAttributes {
            get {
                return ((string)(this["ServerAttributes"]));
            }
            set {
                this["ServerAttributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"screen mode id:i:2
session bpp:i:15
full address:s:{0}
username:s:{1}
compression:i:1
keyboardhook:i:2
audiomode:i:0
redirectdrives:i:1
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:1
redirectclipboard:i:1
displayconnectionbar:i:1
autoreconnection enabled:i:1
authentication level:i:0
domain:s:{2}
disable wallpaper:i:1
disable full window drag:i:1
disable menu anims:i:1
disable themes:i:1
disable cursor setting:i:0
bitmapcachepersistenable:i:1")]
        public string RdpTemplate {
            get {
                return ((string)(this["RdpTemplate"]));
            }
            set {
                this["RdpTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultRdpDir {
            get {
                return ((string)(this["DefaultRdpDir"]));
            }
            set {
                this["DefaultRdpDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ToClipboard {
            get {
                return ((bool)(this["ToClipboard"]));
            }
            set {
                this["ToClipboard"] = value;
            }
        }
    }
}
